main:
    log_file: ./log/pattoo.log
    log_level: debug
    log_directory: ./log
    agent_cache_directory: ./cache
    language: en
    interval: 15

passived:
    listen_address: 127.0.0.1
    bind_port: 5000

actived:
    api_server_name: 127.0.0.1
    api_server_port: 6000
    api_server_https: False
    api_server_uri: /pattoo/api/v1
    
